### PR TITLE
Feature --viewport-width --viewport-height options

### PR DESCRIPTION
**Pull request by wmhilton**
For issue #409

### CODE REVIEW

**Comment by wmhilton** [comment]
I updated documentation. Are there unit tests for command line options?

**Comment by laurentj** [comment]
I'm ok with this patch, but you should rebase the branch to be able to merge it

**Comment by laurentj** [comment]
No, there are not tests for command line options...

**Comment by wmhilton** [comment]
Rebased! :)

**Comment by laurentj** [comment]
Thank you !

**Pull request merged**
