### PR TITLE
Issue 50 - User defined exit codes

### PR DESCRIPTION
**Pull request by abozhilov**
Checkout tests https://github.com/abozhilov/slimerjs-exit 

For the Windows .bat file I'm not sure how to implement exit status. Don't know if it even supported.

### CODE REVIEW

**Comment by masi** [comment]
In a batch file use `EXIT /B [code]`.

**Comment by bensu** [comment]
I'm wondering if this PR made it into the latest release. Looking at the source for [`0.9.6`](https://github.com/laurentj/slimerjs/releases/tag/RELEASE_0.9.6) it doesn't look like it did, even though the merge data < release date by a couple of months.

**Comment by laurentj** [comment]
@bensu no, only in the master branch

**Comment by bensu** [comment]
Thanks @laurentj ! I'll wait for the next release then.

**Pull request merged**
