### PR TITLE
Run tests in CI

### PR DESCRIPTION
**Pull request by Paxa**
I didn't find any automated test server, so I created one. It runs with a docker so it's easy to run same setup on local computer. In case you are interested in this thing

### CODE REVIEW

**Comment by laurentj** [comment]
Let's try :-)

**Comment by laurentj** [comment]
Result: https://travis-ci.org/laurentj/slimerjs/jobs/209678710

It seems tests have freezed at [the pdf test](https://github.com/laurentj/slimerjs/blob/master/test/test-webpage-render.js#L152). I don't know why... I had to cancel the job after few minutes...

**Comment by Paxa** [comment]
I run it with --debug=true and it print `Gtk-WARNING **: Unknown paper size Custom`, tried to install `libpaper`, doesn't help, may be it stuck in other part

I also try to run firefox 52 with centos and it can pass that, but give error on other step

**Comment by Paxa** [comment]
I put it here
https://github.com/Paxa/slimerjs/tree/docker-centos
https://travis-ci.org/Paxa/slimerjs/builds/212055405

**Pull request merged**
