### PR TITLE
rename npm package back to slimerjs

### PR DESCRIPTION
**Pull request by graingert**
I'm just waiting on @laurentj to confirm his npm name.

### CODE REVIEW

**Comment by laurentj** [comment]
I confirm my account is [laurentj](https://www.npmjs.com/~laurentj)

What should I do now?

**Comment by graingert** [comment]
Wait for me to add you ;)

**Comment by graingert** [comment]
I'm afk right now

**Comment by graingert** [comment]
> What should I do now?

1. add a gravatar to  dev@ljouanneau.com
2. you should be able to run `npm publish` in the cloned repo.

**Pull request merged**
