### PR TITLE
Update MaxVersion to 51

### PR DESCRIPTION
**Pull request by Paxa**

### CODE REVIEW

**Comment by Paxa** [comment]
I try to run tests in travis-ci and some fail:
https://travis-ci.org/Paxa/slimerjs/builds/205735828

Is it expected?

**Comment by laurentj** [comment]
no, it is not expected. see #579

**Comment by laurentj** [comment]
I fixed all issues about compatibility with Fx51 and Fx52, and updated the application.ini

**Comment by jefleponot** [comment]
thanks

**Pull request closed without merging**
